### ISSUE TITLE
直接报空指针

### ISSUE THREAD

**Issue by sorgs** [jokermonn/permissions4m#24]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.sokal.zouhonglive, PID: 20155
                                                                       java.lang.NullPointerException: Attempt to invoke interface method 'void com.joker.api.wrapper.AnnotationWrapper$PermissionsProxy.granted(java.lang.Object, int)' on a null object reference
                                                                           at com.joker.api.apply.NormalApplyPermissions.grantedWithAnnotation(NormalApplyPermissions.java:27)
                                                                           at com.joker.api.wrapper.AbstractWrapper.requestPermissionWithAnnotation(AbstractWrapper.java:315)
                                                                           at com.joker.api.wrapper.AbstractWrapper.request(AbstractWrapper.java:203)
                                                                           at com.sokal.zouhonglive.view.MainActivity.requestPermission(MainActivity.java:145)
                                                                           at com.sokal.zouhonglive.view.MainActivity.onClick(MainActivity.java:123)
                                                                           at com.sokal.zouhonglive.view.MainActivity_ViewBinding$3.doClick(MainActivity_ViewBinding.java:60)
                                                                           at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                           at android.view.View.performClick(View.java:4848)
                                                                           at android.view.View$PerformClick.run(View.java:20262)
                                                                           at android.os.Handler.handleCallback(Handler.java:815)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                           at android.os.Looper.loop(Looper.java:194)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5644)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by itwangyu** [comment]
我也遇到了 ,demo是好的  不知道为啥自己一用就空指针

**Comment by sorgs** [comment]
我已经发现问题了，就是没有把注解的方法调用完。报错的方法没有掉，就报了空指针。
不过好羡慕楼主啊，同样是大四，天一样的差别。

**Comment by jokermonn** [comment]
不好意思，手机型号，使用场景可以报一下吗。不用羡慕我，差点没找到工作

**Comment by sorgs** [comment]
和手机机型无关。就是你没有说有些方法是必须调用的才可以。这个问题经过我多次尝试已经解决了。
你的差点没找到工作是因为工作和工作是有区别的。我现在还处于别人轮子都用不好的阶段，大佬已经开始造轮子了，真的差别太大了

**Comment by jokermonn** [comment]
谢谢反馈，共同加油~
